bldr:
    profiles:
        default:
            description: 'Development Profile'
            jobs:
                - prepare
                - lint
                - phpcs
                - test
        test:
            description: "Test Profile"
            jobs:
                - testDev
        watch:
            description: "Watch Profile"
            uses:
                before:
                    - test
            jobs:
                - watch
        buildPhar:
            description: Builds the phar
            jobs:
                - buildPhar
        release:
            description: Releases Bldr
            uses:
                after:
                    - buildPhar
            jobs:
                - release
        functionalTest:
            description: used for running a functional test on bldr
            jobs:
                - fsTest
                - lint