#!/usr/bin/env bash

if [ ! -d "$(pwd)/.git" ]; then
    echo "Execute in the main directory please"
    exit
fi

if [ ! -d $(pwd)/bldr-phar ]; then
    echo "Cloning Bldr Phar repo"
    git clone git@github.com:bldr-io/bldr-phar.git
fi

./bin/box build

if [ ! -f $(pwd)/bldr.phar ]; then
    echo "Failed creating phar file"
    exit
fi

cd bldr-phar
git checkout master

if [ $1 == '$RELEASE_VERSION$' ]; then
    mkdir -p dev
    cp ../bldr.phar ./dev/
    git add dev/bldr.phar -f
    git commit -m "Updating Phar"
    git push origin master
else
    mkdir -p $1
    cp ../bldr.phar ./$1/
    git add $1/bldr.phar -f
    git commit -m "Updating Phar"
    git push origin master

    cp ../bldr.phar ./stable/
    git add stable/bldr.phar -f
    git commit -m "Updating Phar"
    git push origin master
fi

cd -